const entry = (id, name, options = {}) => ({ id, name, ...options });

export const POWER_LEVELS = [
  { id: "sub-human", name: "Sub-Human", minimum: 0, maximum: 24, sourcePage: 22 },
  { id: "human", name: "Human", minimum: 25, maximum: 49, sourcePage: 22 },
  { id: "adventurer", name: "Adventurer", minimum: 50, maximum: 74, sourcePage: 22 },
  { id: "heroic", name: "Heroic", minimum: 75, maximum: 99, sourcePage: 22 },
  { id: "mythical", name: "Mythical", minimum: 100, maximum: 149, sourcePage: 22 },
  { id: "superhuman", name: "Superhuman", minimum: 150, maximum: 199, sourcePage: 23 },
  { id: "superpowered", name: "Superpowered", minimum: 200, maximum: 249, sourcePage: 23 },
  { id: "godlike", name: "Godlike", minimum: 250, maximum: null, sourcePage: 23 }
];

export const TARGET_NUMBERS = [
  { label: "Simple", value: 6, sourcePage: 177 },
  { label: "Easy", value: 9, sourcePage: 177 },
  { label: "Average", value: 12, sourcePage: 177 },
  { label: "Difficult", value: 15, sourcePage: 177 },
  { label: "Challenging", value: 18, sourcePage: 177 },
  { label: "Unlikely", value: 21, sourcePage: 177 },
  { label: "Improbable", value: 24, sourcePage: 177 }
];

export const SIZE_RANKS = {
  "-10": { rank: -10, label: "Mote", pointCost: -100, strengthDamage: -100, defenceRangedMod: 20, attackRangedMod: 20, durability: -100, rangeSpeedMultiplier: 0.001, liftingMultiplier: 1 / 5000000, sourcePage: 35 },
  "-9": { rank: -9, label: "Speck", pointCost: -90, strengthDamage: -90, defenceRangedMod: 18, attackRangedMod: 18, durability: -90, rangeSpeedMultiplier: 0.002, liftingMultiplier: 1 / 1000000, sourcePage: 35 },
  "-8": { rank: -8, label: "Minute", pointCost: -80, strengthDamage: -80, defenceRangedMod: 16, attackRangedMod: 16, durability: -80, rangeSpeedMultiplier: 0.004, liftingMultiplier: 1 / 250000, sourcePage: 35 },
  "-7": { rank: -7, label: "Wee", pointCost: -70, strengthDamage: -70, defenceRangedMod: 14, attackRangedMod: 14, durability: -70, rangeSpeedMultiplier: 0.008, liftingMultiplier: 1 / 50000, sourcePage: 35 },
  "-6": { rank: -6, label: "Teeny", pointCost: -60, strengthDamage: -60, defenceRangedMod: 12, attackRangedMod: 12, durability: -60, rangeSpeedMultiplier: 1 / 60, liftingMultiplier: 1 / 10000, sourcePage: 35 },
  "-5": { rank: -5, label: "Fine", pointCost: -50, strengthDamage: -50, defenceRangedMod: 10, attackRangedMod: 10, durability: -50, rangeSpeedMultiplier: 1 / 30, liftingMultiplier: 1 / 2500, sourcePage: 35 },
  "-4": { rank: -4, label: "Diminutive", pointCost: -40, strengthDamage: -40, defenceRangedMod: 8, attackRangedMod: 8, durability: -40, rangeSpeedMultiplier: 1 / 15, liftingMultiplier: 1 / 500, sourcePage: 35 },
  "-3": { rank: -3, label: "Tiny", pointCost: -30, strengthDamage: -30, defenceRangedMod: 6, attackRangedMod: 6, durability: -30, rangeSpeedMultiplier: 1 / 8, liftingMultiplier: 1 / 100, sourcePage: 35 },
  "-2": { rank: -2, label: "Small", pointCost: -20, strengthDamage: -20, defenceRangedMod: 4, attackRangedMod: 4, durability: -20, rangeSpeedMultiplier: 0.25, liftingMultiplier: 1 / 25, sourcePage: 35 },
  "-1": { rank: -1, label: "Small", pointCost: -10, strengthDamage: -10, defenceRangedMod: 2, attackRangedMod: 2, durability: -10, rangeSpeedMultiplier: 0.5, liftingMultiplier: 0.2, sourcePage: 35 },
  "0": { rank: 0, label: "Medium", pointCost: 0, strengthDamage: 0, defenceRangedMod: 0, attackRangedMod: 0, durability: 0, rangeSpeedMultiplier: 1, liftingMultiplier: 1, sourcePage: 35 },
  "1": { rank: 1, label: "Large", pointCost: 10, strengthDamage: 10, defenceRangedMod: -2, attackRangedMod: -2, durability: 10, rangeSpeedMultiplier: 2, liftingMultiplier: 5, sourcePage: 35 },
  "2": { rank: 2, label: "Huge", pointCost: 20, strengthDamage: 20, defenceRangedMod: -4, attackRangedMod: -4, durability: 20, rangeSpeedMultiplier: 4, liftingMultiplier: 25, sourcePage: 35 },
  "3": { rank: 3, label: "Mammoth", pointCost: 30, strengthDamage: 30, defenceRangedMod: -6, attackRangedMod: -6, durability: 30, rangeSpeedMultiplier: 8, liftingMultiplier: 100, sourcePage: 35 },
  "4": { rank: 4, label: "Gigantic", pointCost: 40, strengthDamage: 40, defenceRangedMod: -8, attackRangedMod: -8, durability: 40, rangeSpeedMultiplier: 15, liftingMultiplier: 500, sourcePage: 35 },
  "5": { rank: 5, label: "Gargantuan", pointCost: 50, strengthDamage: 50, defenceRangedMod: -10, attackRangedMod: -10, durability: 50, rangeSpeedMultiplier: 30, liftingMultiplier: 2500, sourcePage: 35 },
  "6": { rank: 6, label: "Colossal", pointCost: 60, strengthDamage: 60, defenceRangedMod: -12, attackRangedMod: -12, durability: 60, rangeSpeedMultiplier: 60, liftingMultiplier: 10000, sourcePage: 35 },
  "7": { rank: 7, label: "Enormous", pointCost: 70, strengthDamage: 70, defenceRangedMod: -14, attackRangedMod: -14, durability: 70, rangeSpeedMultiplier: 125, liftingMultiplier: 50000, sourcePage: 35 },
  "8": { rank: 8, label: "Monstrous", pointCost: 80, strengthDamage: 80, defenceRangedMod: -16, attackRangedMod: -16, durability: 80, rangeSpeedMultiplier: 250, liftingMultiplier: 250000, sourcePage: 35 },
  "9": { rank: 9, label: "Titanic", pointCost: 90, strengthDamage: 90, defenceRangedMod: -18, attackRangedMod: -18, durability: 90, rangeSpeedMultiplier: 500, liftingMultiplier: 1000000, sourcePage: 35 },
  "10": { rank: 10, label: "Monumental", pointCost: 100, strengthDamage: 100, defenceRangedMod: -20, attackRangedMod: -20, durability: 100, rangeSpeedMultiplier: 1000, liftingMultiplier: 5000000, sourcePage: 35 }
};

export const SKILL_GROUPS = {
  academic: { id: "academic", name: "Academic", costPerLevel: 1, category: "background", sourcePage: 120 },
  artistic: { id: "artistic", name: "Artistic", costPerLevel: 1, category: "background", sourcePage: 120 },
  domestic: { id: "domestic", name: "Domestic", costPerLevel: 1, category: "background", sourcePage: 120 },
  occupation: { id: "occupation", name: "Occupation", costPerLevel: 1, category: "background", sourcePage: 120 },
  business: { id: "business", name: "Business", costPerLevel: 2, category: "field", sourcePage: 121 },
  social: { id: "social", name: "Social", costPerLevel: 2, category: "field", sourcePage: 121 },
  street: { id: "street", name: "Street", costPerLevel: 2, category: "field", sourcePage: 121 },
  technical: { id: "technical", name: "Technical", costPerLevel: 2, category: "field", sourcePage: 121 },
  adventuring: { id: "adventuring", name: "Adventuring", costPerLevel: 3, category: "action", sourcePage: 121 },
  detective: { id: "detective", name: "Detective", costPerLevel: 3, category: "action", sourcePage: 121 },
  military: { id: "military", name: "Military", costPerLevel: 3, category: "action", sourcePage: 121 },
  scientific: { id: "scientific", name: "Scientific", costPerLevel: 3, category: "action", sourcePage: 121 }
};

export const ATTRIBUTE_CATALOG = {
  absorption: entry("absorption", "Absorption", { costType: "perLevel", costPerLevel: 5, relevantStat: "body", sourcePage: 78 }),
  "alternate-form": entry("alternate-form", "Alternate Form", { costType: "perLevel", costPerLevel: 4, relevantStat: "body", sourcePage: 78 }),
  "alternate-identity": entry("alternate-identity", "Alternate Identity", { costType: "perLevel", costPerLevel: 1, relevantStat: "body", sourcePage: 80, humanCompatible: true }),
  armour: entry("armour", "Armour", { costType: "perLevel", costPerLevel: 2, sourcePage: 80, automation: { armourRatingPerLevel: 5 } }),
  "attack-mastery": entry("attack-mastery", "Attack Mastery", { costType: "perLevel", costPerLevel: 1, sourcePage: 80, humanCompatible: true, automation: { attackCombatValuePerLevel: 1 } }),
  augmented: entry("augmented", "Augmented", { costType: "perLevel", costPerLevel: 2, sourcePage: 80, automation: { augmentsSelectedStatPerLevel: 1 } }),
  capacity: entry("capacity", "Capacity", { costType: "perLevel", costPerLevel: 1, sourcePage: 81 }),
  "change-state": entry("change-state", "Change State", { costType: "perLevel", costPerLevel: 3, relevantStat: "body", sourcePage: 82 }),
  cognition: entry("cognition", "Cognition", { costType: "perLevel", costPerLevel: 2, relevantStat: "mind", sourcePage: 82 }),
  "combat-technique": entry("combat-technique", "Combat Technique", { costType: "perLevel", costPerLevel: 1, sourcePage: 83, humanCompatible: true }),
  companion: entry("companion", "Companion", { costType: "perLevel", costPerLevel: 4, sourcePage: 84, humanCompatible: true }),
  connected: entry("connected", "Connected", { costType: "perLevel", costPerLevel: 1, sourcePage: 84, humanCompatible: true }),
  "control-environment": entry("control-environment", "Control Environment", { costType: "perLevel", costPerLevel: 1, relevantStat: "mind", sourcePage: 86 }),
  conversion: entry("conversion", "Conversion", { costType: "perLevel", costPerLevel: 3, relevantStat: "body", sourcePage: 86 }),
  "data-access": entry("data-access", "Data Access", { costType: "perLevel", costPerLevel: 2, relevantStat: "mind", sourcePage: 88 }),
  "defence-mastery": entry("defence-mastery", "Defence Mastery", { costType: "perLevel", costPerLevel: 1, sourcePage: 88, humanCompatible: true, automation: { defenceCombatValuePerLevel: 1 } }),
  "dimension-walk": entry("dimension-walk", "Dimension Walk", { costType: "perLevel", costPerLevel: 5, relevantStat: "soul", sourcePage: 89 }),
  "dynamic-powers": entry("dynamic-powers", "Dynamic Powers", { costType: "perLevel", costPerLevel: 10, relevantStat: "soul", sourcePage: 89 }),
  elasticity: entry("elasticity", "Elasticity", { costType: "perLevel", costPerLevel: 1, sourcePage: 90 }),
  "enemy-attack": entry("enemy-attack", "Enemy Attack", { costType: "perLevel", costPerLevel: 1, sourcePage: 90, humanCompatible: true }),
  "enemy-defence": entry("enemy-defence", "Enemy Defence", { costType: "perLevel", costPerLevel: 1, sourcePage: 90, humanCompatible: true }),
  energised: entry("energised", "Energised", { costType: "perLevel", costPerLevel: 1, sourcePage: 91, humanCompatible: true, automation: { energyPointsPerLevel: 10 } }),
  exorcism: entry("exorcism", "Exorcism", { costType: "perLevel", costPerLevel: 1, relevantStat: "soul", sourcePage: 91 }),
  "extra-actions": entry("extra-actions", "Extra Actions", { costType: "perLevel", costPerLevel: 4, sourcePage: 92, humanCompatible: true, automation: { actionsPerLevel: 1 } }),
  "extra-arms": entry("extra-arms", "Extra Arms", { costType: "perLevel", costPerLevel: 1, sourcePage: 92 }),
  features: entry("features", "Features", { costType: "perLevel", costPerLevel: 1, sourcePage: 92, humanCompatible: true }),
  flight: entry("flight", "Flight", { costType: "perLevel", costPerLevel: 3, relevantStat: "body", sourcePage: 94, automation: { movementProfile: "flight" } }),
  "force-field": entry("force-field", "Force Field", { costType: "perLevel", costPerLevel: 4, sourcePage: 94, automation: { armourRatingPerLevel: 10 } }),
  gear: entry("gear", "Gear", { costType: "perLevel", costPerLevel: 1, sourcePage: 95, humanCompatible: true }),
  "ground-speed": entry("ground-speed", "Ground Speed", { costType: "perLevel", costPerLevel: 1, sourcePage: 96, automation: { movementProfile: "ground" } }),
  healing: entry("healing", "Healing", { costType: "perLevel", costPerLevel: 1, relevantStat: "soul", sourcePage: 96 }),
  "heightened-awareness": entry("heightened-awareness", "Heightened Awareness", { costType: "perLevel", costPerLevel: 1, relevantStat: "mind", sourcePage: 97, humanCompatible: true }),
  "heightened-senses": entry("heightened-senses", "Heightened Senses", { costType: "perLevel", costPerLevel: 1, relevantStat: "mind", sourcePage: 97 }),
  illusion: entry("illusion", "Illusion", { costType: "perLevel", costPerLevel: 1, relevantStat: "mind", sourcePage: 97 }),
  immunity: entry("immunity", "Immunity", { costType: "perLevel", costPerLevel: 3, sourcePage: 98 }),
  immutable: entry("immutable", "Immutable", { costType: "perLevel", costPerLevel: 1, sourcePage: 99 }),
  inspire: entry("inspire", "Inspire", { costType: "perLevel", costPerLevel: 1, relevantStat: "soul", sourcePage: 99, humanCompatible: true }),
  item: entry("item", "Item", { costType: "special", sourcePage: 101, humanCompatible: true }),
  jumping: entry("jumping", "Jumping", { costType: "perLevel", costPerLevel: 1, sourcePage: 101 }),
  "massive-damage": entry("massive-damage", "Massive Damage", { costType: "perLevel", costPerLevel: 3, sourcePage: 102, humanCompatible: true, automation: { damageMultiplierPerLevel: 1 } }),
  "melee-attack": entry("melee-attack", "Melee Attack", { costType: "perLevel", costPerLevel: 1, sourcePage: 102, humanCompatible: true }),
  "melee-defence": entry("melee-defence", "Melee Defence", { costType: "perLevel", costPerLevel: 1, sourcePage: 103, humanCompatible: true }),
  merge: entry("merge", "Merge", { costType: "perLevel", costPerLevel: 4, relevantStat: "body", sourcePage: 103 }),
  metamorphosis: entry("metamorphosis", "Metamorphosis", { costType: "perLevel", costPerLevel: 2, relevantStat: "body", sourcePage: 106 }),
  mimic: entry("mimic", "Mimic", { costType: "perLevel", costPerLevel: 2, relevantStat: "mind", sourcePage: 107 }),
  "mind-control": entry("mind-control", "Mind Control", { costType: "perLevel", costPerLevel: 5, relevantStat: "mind", sourcePage: 108 }),
  "mind-shield": entry("mind-shield", "Mind Shield", { costType: "perLevel", costPerLevel: 1, relevantStat: "mind", sourcePage: 109, humanCompatible: true }),
  minions: entry("minions", "Minions", { costType: "perLevel", costPerLevel: 2, sourcePage: 109, humanCompatible: true }),
  mulligan: entry("mulligan", "Mulligan", { costType: "perLevel", costPerLevel: 1, relevantStat: "soul", sourcePage: 109, humanCompatible: true }),
  nullify: entry("nullify", "Nullify", { costType: "perLevel", costPerLevel: 5, relevantStat: "mind", sourcePage: 110 }),
  "plant-control": entry("plant-control", "Plant Control", { costType: "perLevel", costPerLevel: 1, relevantStat: "soul", sourcePage: 110 }),
  "pocket-dimension": entry("pocket-dimension", "Pocket Dimension", { costType: "perLevel", costPerLevel: 1, sourcePage: 112 }),
  portal: entry("portal", "Portal", { costType: "perLevel", costPerLevel: 2, relevantStat: "mind", sourcePage: 112 }),
  "power-flux": entry("power-flux", "Power Flux", { costType: "perLevel", costPerLevel: 10, relevantStat: "soul", sourcePage: 113 }),
  "power-variation": entry("power-variation", "Power Variation", { costType: "perLevel", costPerLevel: 4, relevantStat: "mind", sourcePage: 114 }),
  projection: entry("projection", "Projection", { costType: "perLevel", costPerLevel: 3, relevantStat: "mind", sourcePage: 114 }),
  "ranged-attack": entry("ranged-attack", "Ranged Attack", { costType: "perLevel", costPerLevel: 1, sourcePage: 116, humanCompatible: true }),
  "ranged-defence": entry("ranged-defence", "Ranged Defence", { costType: "perLevel", costPerLevel: 1, sourcePage: 116, humanCompatible: true }),
  regeneration: entry("regeneration", "Regeneration", { costType: "perLevel", costPerLevel: 5, sourcePage: 117 }),
  reincarnation: entry("reincarnation", "Reincarnation", { costType: "perLevel", costPerLevel: 2, sourcePage: 117 }),
  resilient: entry("resilient", "Resilient", { costType: "perLevel", costPerLevel: 2, relevantStat: "body", sourcePage: 118 }),
  "sensory-block": entry("sensory-block", "Sensory Block", { costType: "perLevel", costPerLevel: 1, relevantStat: "mind", sourcePage: 119 }),
  "sixth-sense": entry("sixth-sense", "Sixth Sense", { costType: "perLevel", costPerLevel: 1, relevantStat: "soul", sourcePage: 119 }),
  "size-change": entry("size-change", "Size Change", { costType: "perLevel", costPerLevel: 10, relevantStat: "body", sourcePage: 120, automation: { sizeRankPerLevel: 1 } }),
  "skill-group": entry("skill-group", "Skill Group", { costType: "skillGroup", sourcePage: 120, humanCompatible: true }),
  spaceflight: entry("spaceflight", "Spaceflight", { costType: "perLevel", costPerLevel: 1, relevantStat: "body", sourcePage: 121, automation: { movementProfile: "spaceflight" } }),
  "special-movement": entry("special-movement", "Special Movement", { costType: "perLevel", costPerLevel: 1, sourcePage: 122 }),
  "summon-creatures": entry("summon-creatures", "Summon Creatures", { costType: "perLevel", costPerLevel: 2, relevantStat: "soul", sourcePage: 122 }),
  supersense: entry("supersense", "Supersense", { costType: "perLevel", costPerLevel: 1, sourcePage: 123 }),
  superspeed: entry("superspeed", "Superspeed", { costType: "perLevel", costPerLevel: 3, sourcePage: 123, automation: { movementProfile: "superspeed" } }),
  superstrength: entry("superstrength", "Superstrength", { costType: "perLevel", costPerLevel: 4, sourcePage: 124, automation: { muscleDamageMultiplierPerLevel: 1, unarmedDamagePerLevel: 5 } }),
  swarm: entry("swarm", "Swarm", { costType: "perLevel", costPerLevel: 2, sourcePage: 124 }),
  telekinesis: entry("telekinesis", "Telekinesis", { costType: "perLevel", costPerLevel: 4, relevantStat: "mind", sourcePage: 125 }),
  telepathy: entry("telepathy", "Telepathy", { costType: "perLevel", costPerLevel: 3, relevantStat: "mind", sourcePage: 126 }),
  teleport: entry("teleport", "Teleport", { costType: "perLevel", costPerLevel: 3, relevantStat: "body", sourcePage: 127 }),
  tough: entry("tough", "Tough", { costType: "perLevel", costPerLevel: 1, sourcePage: 128, humanCompatible: true, automation: { healthPointsPerLevel: 10 } }),
  transfer: entry("transfer", "Transfer", { costType: "perLevel", costPerLevel: 3, relevantStat: "soul", sourcePage: 128 }),
  transmute: entry("transmute", "Transmute", { costType: "perLevel", costPerLevel: 3, relevantStat: "mind", sourcePage: 128 }),
  tunnelling: entry("tunnelling", "Tunnelling", { costType: "perLevel", costPerLevel: 1, sourcePage: 129 }),
  unaffected: entry("unaffected", "Unaffected", { costType: "perLevel", costPerLevel: 2, sourcePage: 129 }),
  undetectable: entry("undetectable", "Undetectable", { costType: "perLevel", costPerLevel: 2, sourcePage: 131 }),
  "unique-attribute": entry("unique-attribute", "Unique Attribute", { costType: "variable", sourcePage: 131, humanCompatible: true }),
  "unknown-power": entry("unknown-power", "Unknown Power", { costType: "variable", sourcePage: 123, humanCompatible: true }),
  "water-speed": entry("water-speed", "Water Speed", { costType: "perLevel", costPerLevel: 1, sourcePage: 132, automation: { movementProfile: "water" } }),
  wealth: entry("wealth", "Wealth", { costType: "perLevel", costPerLevel: 3, sourcePage: 132, humanCompatible: true }),
  weapon: entry("weapon", "Weapon", { costType: "perLevel", costPerLevel: 2, relevantStat: "body", sourcePage: 132, isAttack: true })
};

export const DEFECT_CATALOG = {
  "achilles-heel": entry("achilles-heel", "Achilles Heel", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 156 }),
  "awkward-size": entry("awkward-size", "Awkward Size", { category: "greater", costType: "special", sourcePage: 156 }),
  bane: entry("bane", "Bane", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 156 }),
  "blind-fury": entry("blind-fury", "Blind Fury", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 157 }),
  "conditional-ownership": entry("conditional-ownership", "Conditional Ownership", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 157 }),
  confined: entry("confined", "Confined", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 158 }),
  cursed: entry("cursed", "Cursed", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 158 }),
  "easily-distracted": entry("easily-distracted", "Easily Distracted", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 158 }),
  fragile: entry("fragile", "Fragile", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 158, automation: { healthPointsPerRank: -10 } }),
  hounded: entry("hounded", "Hounded", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 158 }),
  "impaired-manipulation": entry("impaired-manipulation", "Impaired Manipulation", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 158 }),
  "impaired-speech": entry("impaired-speech", "Impaired Speech", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 160 }),
  "inept-attack": entry("inept-attack", "Inept Attack", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 160, automation: { attackCombatValuePerRank: -1 } }),
  "inept-defence": entry("inept-defence", "Inept Defence", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 160, automation: { defenceCombatValuePerRank: -1 } }),
  "involuntary-change": entry("involuntary-change", "Involuntary Change", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 160 }),
  ism: entry("ism", "Ism", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 160 }),
  magnet: entry("magnet", "Magnet", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 161 }),
  marked: entry("marked", "Marked", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 161 }),
  nemesis: entry("nemesis", "Nemesis", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 161 }),
  nightmares: entry("nightmares", "Nightmares", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 161 }),
  obligated: entry("obligated", "Obligated", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 163 }),
  phobia: entry("phobia", "Phobia", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 163 }),
  "physical-impairment": entry("physical-impairment", "Physical Impairment", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 163 }),
  "red-tape": entry("red-tape", "Red Tape", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 163 }),
  "reduced-damage": entry("reduced-damage", "Reduced Damage", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 163, automation: { damageMultiplierPerRank: -1 } }),
  "sensory-impairment": entry("sensory-impairment", "Sensory Impairment", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 164 }),
  shortcoming: entry("shortcoming", "Shortcoming", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 164 }),
  "significant-other": entry("significant-other", "Significant Other", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 165 }),
  "skeleton-in-the-closet": entry("skeleton-in-the-closet", "Skeleton in the Closet", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 165 }),
  "social-fault": entry("social-fault", "Social Fault", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 166 }),
  "special-requirement": entry("special-requirement", "Special Requirement", { category: "serious", pointsByRank: [-3, -6, -9], sourcePage: 166 }),
  unappealing: entry("unappealing", "Unappealing", { category: "lesser", pointsByRank: [-1, -2, -3], sourcePage: 166 }),
  "unique-defect": entry("unique-defect", "Unique Defect", { category: "special", costType: "special", sourcePage: 167 }),
  vulnerability: entry("vulnerability", "Vulnerability", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 167 }),
  wanted: entry("wanted", "Wanted", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 167 }),
  "weak-point": entry("weak-point", "Weak Point", { category: "greater", pointsByRank: [-2, -4, -6], sourcePage: 167 })
};
